server:
  port: 8085

spring:
  application:
    name: event-processor
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jitsu_db}
    username: ${SPRING_DATASOURCE_USERNAME:jitsu_user}
    password: ${SPRING_DATASOURCE_PASSWORD:jitsu_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: event-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.jitsu.common.event

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.jitsu: DEBUG