server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/booking-sessions/**
        - id: ticket-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/tickets/**
        - id: assignment-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/assignments/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG